import React from "react";


// ---------- Product catalog data ----------
export const PRODUCTS = [
  // EVAPORATIVE COOLERS
  {
    id: "scmxl-18000",
    category: "evap",
    series: "Evaporativos",
    name: "SCMXL 18000",
    tagline: "Enfriador portátil de alto rendimiento",
    desc: "Flujo de aire máximo industrial con control digital, modo swing y temporizador. Pensado para áreas amplias de uso continuo.",
    art: "Cooler",
    images: [
      "/assets/products/scmxl-18000/1.png",
      "/assets/products/scmxl-18000/2.png",
      "/assets/products/scmxl-18000/3.png",
      "/assets/products/scmxl-18000/4.png",
      "/assets/products/scmxl-18000/5.png",
      "/assets/products/scmxl-18000/6.png",
      "/assets/products/scmxl-18000/7.png",
      "/assets/products/scmxl-18000/8.png",
      "/assets/products/scmxl-18000/medidas.png",
      "/assets/products/scmxl-18000/ficha.png",
    ],
    keySpecs: [
      { k: "Flujo de aire máximo", v: "18.000", u: "m³/h" },
      { k: "Cobertura", v: "Hasta", u: "200 m²" },
    ],
    specs: [
      ["Flujo de aire máximo", "18 000 m³/h"],
      ["CFM", "10 600"],
      ["Frecuencia", "60 Hz"],
      ["Consumo eléctrico", "550 W"],
      ["Tipo de ventilador", "Axial"],
      ["Consumo de agua", "10 – 15 L/h"],
      ["Capacidad de agua", "90 L"],
      ["Dimensiones", "1120 × 690 × 1630 mm"],
      ["Peso", "57 kg"],
      ["Área de enfriamiento", "150 – 200 m²"],
      ["Velocidades", "3"],
      ["Sensor de nivel de agua", "Sí"],
      ["Protección de bomba de agua", "Sí"],
      ["Difusor", "Doble / Swing"],
      ["Temporizador", "Hasta 24 horas"],
    ],
    features: [
      { i: "Remote", t: "Control digital + remoto" },
      { i: "Gauge", t: "3 velocidades configurables" },
      { i: "Timer", t: "Temporizador programable" },
      { i: "Drop", t: "Protección de bomba de agua" },
      { i: "Wind", t: "Modo swing oscilatorio" },
    ],
  },
  {
    id: "clasico-18000",
    category: "evap",
    series: "Evaporativos",
    name: "Clásico 18000",
    tagline: "Formato clásico, estructura robusta",
    desc: "Enfriador evaporativo de geometría tradicional pensado para entornos comerciales e industriales exigentes.",
    art: "Cooler",
    images: [
      "/assets/products/clasico-18000/1.png",
      "/assets/products/clasico-18000/2.png",
      "/assets/products/clasico-18000/3.png",
      "/assets/products/clasico-18000/4.png",
      "/assets/products/clasico-18000/5.png",
      "/assets/products/clasico-18000/6.png",
      "/assets/products/clasico-18000/7.png",
      "/assets/products/clasico-18000/8.png",
      "/assets/products/clasico-18000/medidas.png",
      "/assets/products/clasico-18000/ficha.png",
    ],
    keySpecs: [
      { k: "Flujo de aire máximo", v: "18.000", u: "m³/h" },
      { k: "Cobertura", v: "Hasta", u: "200 m²" },
    ],
    specs: [
      ["Flujo de aire máximo", "18 000 m³/h"],
      ["CFM", "10 600"],
      ["Frecuencia", "60 Hz"],
      ["Consumo eléctrico", "550 W"],
      ["Estilo de ventilador", "Axial"],
      ["Consumo de agua", "10  a 15 lts/hora"],
      ["Capacidad de agua", "90 lts"],
      ["Dimensiones", "1120 x 690 x 1630 mm"],
      ["Peso", "57 kg"],
      ["Área de enfriamiento", "150 - 200 m²"],
      ["Velocidades", "3"],
      ["Difusor", "Cuádruple / Swing"],
      ["Control remoto", "Sí"],
      ["Función ANION", "Sí"],
      ["Aplicación", "Industrial / Residencial"],
    ],
    features: [
      { i: "Bolt", t: "Estructura industrial reforzada" },
      { i: "Gauge", t: "Velocidades configurables" },
      { i: "Drop", t: "Sistema evaporativo de alto rendimiento" },
    ],
  },
  {
    id: "box-18000",
    category: "evap",
    series: "Evaporativos",
    name: "Box 18000",
    tagline: "Evaporativo portátil de alto rendimiento",
    desc: "Equipo evaporativo portátil de alto rendimiento, diseñado para enfriar grandes espacios mediante flujo de aire potente, consumo controlado de agua y operación manual. Ideal para espacios industriales, comerciales, bodegas, talleres, almacenes y áreas amplias que requieren climatización eficiente.",
    art: "CoolerBox",
    images: [
      "/assets/products/box-18000/1.png",
      "/assets/products/box-18000/2.png",
      "/assets/products/box-18000/3.png",
      "/assets/products/box-18000/4.png",
      "/assets/products/box-18000/5.png",
      "/assets/products/box-18000/medidas.png",
      "/assets/products/box-18000/ficha.png",
    ],
    keySpecs: [
      { k: "Flujo de aire máximo", v: "18.000", u: "m³/h" },
      { k: "Área de enfriamiento", v: "150–200", u: "m²" },
    ],
    specs: [
      ["Modelo", "Box-18000"],
      ["Características nominales", "127 V / 60 Hz / 1100 W"],
      ["Flujo de aire máximo", "18 000 m³/h"],
      ["Consumo de agua", "15 L/h"],
      ["Capacidad de tanque", "130 L"],
      ["Distancia de aire", "35 – 40 m"],
      ["Peso neto", "50 kg"],
      ["Área de enfriamiento", "150 – 200 m²"],
      ["Motor", "3 velocidades / 1 fase"],
      ["Ruido", "63 dB"],
      ["Control", "Manual"],
    ],
    features: [
      { i: "Bolt", t: "Motor 1100 W de alto rendimiento" },
      { i: "Wind", t: "Flujo de aire de 18.000 m³/h, alcance 35–40 m" },
      { i: "Drop", t: "Tanque de 130 L · consumo 15 L/h" },
      { i: "Gauge", t: "3 velocidades · control manual" },
    ],
  },

  {
    id: "slim",
    category: "evap",
    series: "Evaporativos",
    name: "Slim",
    tagline: "Formato estilizado, presencia industrial",
    desc: "Una solución compacta y vertical, ideal para integrarse en espacios donde el espacio es prioridad.",
    art: "Cooler",
    images: [
      "/assets/products/slim/1.png",
      "/assets/products/slim/2.png",
      "/assets/products/slim/medidas.png",
      "/assets/products/slim/ficha.png",
    ],
    keySpecs: [
      { k: "Formato", v: "SLIM", u: "vertical" },
      { k: "Cobertura", v: "hasta", u: "80 m²" },
    ],
    specs: [
      ["Modelo", "Smartercool Slim Fit"],
      ["Formato", "Slim vertical"],
      ["Aplicación", "Comercial e industrial"],
      ["Flujo de aire", "6 000 m³/h"],
      ["CFM", "3 550"],
      ["Consumo eléctrico", "250 W"],
      ["ÁREA DE ENFRIAMIENTO", "50 a 80 m²"],
      ["Dimensiones", "860 x 250 x 1180 mm"],
      ["Peso", "35 kg"],
      ["Toma de corriente", "115 V / 60 Hz"],
      ["Motor", "3 velocidades"],
      ["Ruido", "60 dB"],
    ],
    features: [
      { i: "Wind", t: "Geometría slim para circulación dirigida" },
      { i: "Drop", t: "Sistema evaporativo eficiente" },
      { i: "Gauge", t: "Velocidades configurables" },
    ],
  },
  {
    id: "box-bt",
    category: "evap",
    series: "Evaporativos",
    name: "Box con BT",
    tagline: "Bluetooth · Anion · llenado automático",
    desc: "Enfriador box avanzado con conectividad Bluetooth, modo Anion y llenado de agua automático.",
    art: "CoolerBox",
    images: [
      "/assets/products/box-bt/1.png",
      "/assets/products/box-bt/2.png",
      "/assets/products/box-bt/3.png",
      "/assets/products/box-bt/4.png",
      "/assets/products/box-bt/5.png",
      "/assets/products/box-bt/6.png",
      "/assets/products/box-bt/7.png",
      "/assets/products/box-bt/8.png",
      "/assets/products/box-bt/9.png",
      "/assets/products/box-bt/medidas.png",
      "/assets/products/box-bt/ficha.png",
    ],
    keySpecs: [
      { k: "Conectividad", v: "BT", u: "Bluetooth" },
      { k: "Modos", v: "FRÍO", u: "+ Anion" },
    ],
    specs: [
      ["Conectividad", "Bluetooth"],
      ["Velocidades", "3"],
      ["Swing difusor", "4 posiciones"],
      ["Modos", "Frío + Anion"],
      ["Llenado de agua", "Manual y automático"],
      ["Indicador", "Nivel de agua"],
      ["Control", "Remoto incluido"],
      ["Protección", "Bomba de agua"],
    ],
    features: [
      { i: "Bluetooth", t: "Conectividad Bluetooth integrada" },
      { i: "Wind", t: "Swing difusor de 4 posiciones" },
      { i: "Drop", t: "Llenado manual y automático" },
      { i: "Remote", t: "Control remoto incluido" },
      { i: "Shield", t: "Modo Anion + protección de bomba" },
    ],
  },

  // HVLS FANS
  ...[
    { name: "SC-2600", d: 2.6, b: 5, bw: 14, p: 0.4, v: "220", rpm: 140, flow: 3200, w: 23, area: 180 },
    { name: "SC-3200", d: 3.2, b: 5, bw: 14, p: 0.4, v: "220", rpm: 98, flow: 3600, w: 25, area: 200 },
    { name: "SC-3800", d: 3.8, b: 5, bw: 14, p: 0.4, v: "220", rpm: 80, flow: 3900, w: 30, area: 400 },
    { name: "SC-4200", d: 4.2, b: 5, bw: 14, p: 1.2, v: "220", rpm: 95, flow: 6200, w: 63, area: 500 },
    { name: "SC-5200", d: 5.2, b: 5, bw: 19.4, p: 1.2, v: "220/380", rpm: 75, flow: 8600, w: 78, area: 700 },
    { name: "SC-6300", d: 6.3, b: 6, bw: 19.4, p: 1.4, v: "220/380", rpm: 60, flow: 9800, w: 86, area: 800 },
    { name: "SC-7300", d: 7.3, b: 6, bw: 19.4, p: 1.5, v: "220/380", rpm: 50, flow: 10800, w: 106, area: 900 },
  ].map(m => ({
    id: m.name.toLowerCase(),
    category: "hvls",
    series: "HVLS",
    name: m.name,
    tagline: `Ventilador HVLS · Ø ${m.d} m`,
    desc: `High Volume Low Speed para grandes áreas. ${m.b} aspas, ${m.rpm} RPM, hasta ${m.area} m² de cobertura.`,
    art: "Fan",
    images: [
      "/assets/products/hvls/1.png",
      "/assets/products/hvls/2.png",
      "/assets/products/hvls/3.png",
      "/assets/products/hvls/4.png",
      "/assets/products/hvls/5.png",
      "/assets/products/hvls/6.png",
      "/assets/products/hvls/7.png",
      "/assets/products/hvls/8.png",
      "/assets/products/hvls/9.png",
    ],
    blades: m.b,
    keySpecs: [
      { k: "Diámetro", v: m.d.toString(), u: "m" },
      { k: "Cobertura", v: m.area.toString(), u: "m²" },
    ],
    specs: [
      ["Diámetro", `${m.d} m`],
      ["Número de aspas", m.b.toString()],
      ["Ancho de aspa", `${m.bw} cm`],
      ["Potencia", `${m.p} kW`],
      ["Voltaje", `${m.v} V`],
      ["Velocidad", `${m.rpm} RPM`],
      ["Flujo de aire", `${m.flow}`],
      ["Ruido", "≤ 60 dB"],
      ["Peso", `${m.w} kg`],
      ["Área aplicable", `${m.area} m²`],
    ],
    features: [
      { i: "Wind", t: `Cobertura efectiva hasta ${m.area} m²` },
      { i: "Bolt", t: `Motor ${m.p} kW a ${m.v} V` },
      { i: "Gauge", t: `Operación silenciosa a ${m.rpm} RPM` },
      { i: "Shield", t: "Construcción industrial reforzada" },
    ],
  })),

  // EXTRACTOR
  {
    id: "airmax-gl-50",
    category: "ext",
    series: "Extractores",
    name: "AIRMAX GL 50″",
    tagline: "Extractor industrial · 50 pulgadas",
    desc: "Equipo industrial de alto rendimiento para ventilación eficiente en grandes espacios con altas demandas de circulación.",
    art: "Extractor",
    images: [
      "/assets/products/airmax-gl-50/1.png",
      "/assets/products/airmax-gl-50/2.png",
      "/assets/products/airmax-gl-50/3.png",
      "/assets/products/airmax-gl-50/4.png",
      "/assets/products/airmax-gl-50/medidas.png",
      "/assets/products/airmax-gl-50/ficha.png",
    ],
    keySpecs: [
      { k: "Flujo de aire máximo", v: "44.000", u: "m³/h" },
      { k: "Velocidad", v: "439", u: "RPM" },
    ],
    specs: [
      ["Flujo de aire máximo", "44 000 m³/h"],
      ["Velocidad", "439 RPM"],
      ["Motor", "Industrial monofásico"],
      ["Voltaje", "220 V"],
      ["Potencia", "3/4 HP"],
      ["Operación", "24 / 7"],
      ["Garantía", "1 año"],
      ["Seguridad", "Guardas incluidas"],
      ["Persianas", "Abatibles"],
    ],
    features: [
      { i: "Bolt", t: "Motor monofásico 3/4 HP" },
      { i: "Wind", t: "Flujo de aire máximo de 44.000 m³/h" },
      { i: "Shield", t: "Operación continua 24/7" },
      { i: "Gauge", t: "Persianas abatibles automáticas" },
    ],
  },

  // COOLING PAD
  {
    id: "celdek",
    category: "pad",
    series: "Componentes",
    name: "Cooling Pad Celdek",
    tagline: "Almohadilla evaporativa de celulosa",
    desc: "Alto rendimiento de evaporación, mejor distribución de humedad y vida útil hasta 5× mayor que estándar. Disponible para la mayoría de los equipos evaporativos comerciales del mercado.",
    art: "Pad",
    images: [
      "/assets/products/celdek/1.png",
      "/assets/products/celdek/2.png",
      "/assets/products/celdek/3.png",
      "/assets/products/celdek/4.png",
      "/assets/products/celdek/5.png",
      "/assets/products/celdek/6.png",
      "/assets/products/celdek/7.png",
    ],
    keySpecs: [
      { k: "Vida útil", v: "5×", u: "mayor" },
      { k: "Compatibilidad", v: "Equipos", u: "comerciales" },
    ],
    specs: [
      ["Material", "Celulosa estructurada"],
      ["Vida útil", "Hasta 5× más"],
      ["Densidad", "Alta"],
      ["Función adicional", "Filtra polvo y polen"],
      ["Instalación", "Fácil ajuste"],
      ["Mantenimiento", "Limpieza periódica"],
      ["Compatibilidad", "Mayoría de equipos evaporativos comerciales del mercado"],
    ],
    features: [
      { i: "Drop", t: "Mejora la evaporación" },
      { i: "Shield", t: "Filtra polvo y polen del aire" },
      { i: "Bolt", t: "Hasta 5× más vida útil" },
      { i: "Gauge", t: "Compatible con equipos comerciales del mercado" },
    ],
  },
];

export const CATEGORIES = [
  { id: "evap", name: "Evaporativos", sub: "01 / Enfriamiento", desc: "Enfriadores evaporativos portátiles para áreas amplias.", art: "Cooler", image: "/assets/categories/evap.png" },
  { id: "hvls", name: "HVLS", sub: "02 / Ventilación", desc: "Ventiladores High Volume Low Speed para grandes espacios.", art: "Fan", image: "/assets/categories/hvls.png" },
  { id: "ext", name: "Extractores", sub: "03 / Ventilación Industrial", desc: "Extractores industriales de alto rendimiento.", art: "Extractor", image: "/assets/categories/ext.png" },
  { id: "pad", name: "Cooling Pad", sub: "04 / Componentes", desc: "Almohadillas de enfriamiento y componentes especializados.", art: "Pad", image: "/assets/categories/pad.png" },
];

if (typeof window !== "undefined") {
  Object.assign(window, { PRODUCTS, CATEGORIES });
}
